name: tfvalidate
on:
  push:
    branches:
      - main
    paths:
      - '**.tf'
  pull_request:
    paths:
      - '**.tf'
  workflow_dispatch: # Manual dispatch
permissions:
  contents: read

jobs:
  tfvalidate:
    name: terraform validate
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Install terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_version: 1.3.0

      - name: Validate loadtesting
        working-directory: ./infrastructure/loadtesting/terraform
        run: |
          terraform init -backend=false
          terraform validate

      - name: Validate infrastructure
        working-directory: ./infrastructure/infrastructure/terraform
        run: |
          terraform init -backend=false
          terraform validate
